/*
 * Copyright (c) 2019, 2024, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package jdk.codetools.apidiff.html;

import java.util.Locale;

/**
 * Tags for {@code HtmlTree} nodes.
 *
 * This should be a superset of the tags that may be generated by the standard doclet.
 * However, we still need to be able to cope with unknown tags, such as may be found
 * in user doc-comments.
 */
public enum TagName {
    A,
    B,
    BASE,
    BLOCKQUOTE,
    BODY,
    BR,
    BUTTON,
    CAPTION,
    CITE,
    CODE,
    COL,
    COLGROUP,
    DD,
    DETAILS,
    DFN,
    DIV,
    DL,
    DT,
    EM,
    FOOTER,
    FORM,
    H1, H2, H3, H4, H5, H6,
    HEAD,
    HEADER,
    HR,
    HTML,
    I,
    IMG,
    INPUT,
    LABEL,
    LI,
    LISTING,
    LINK,
    MAIN,
    MENU,
    META,
    NAV,
    NOSCRIPT,
    OL,
    P,
    PRE,
    SAMP,
    SCRIPT,
    SECTION,
    SMALL,
    SPAN,
    STRONG,
    STYLE,
    SUB,
    SUMMARY,
    SUP,
    TABLE,
    TBODY,
    TD,
    TFOOT,
    TH,
    THEAD,
    TITLE,
    TR,
    U,
    UL,
    VAR,
    WBR;

    public static TagName of(String name) {
        return valueOf(name.toUpperCase(Locale.ROOT));
    }
}
