name: Build and Test ApiDiff

on:
  push:
    branches-ignore:
      - master
      - pr/*

jobs:

  linux-x64:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 'Set up Java Development Kit'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17

      - name: 'Build ApiDiff'
        shell: bash
        run: |
          java --version
          bash make/build.sh
