name: 'Test (linux)'

on:
  workflow_call:

jobs:
  test:
    name: 'ApiDiff'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
      - name: 'Set up Java Development Kit'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
      - name: 'Build ApiDiff'
        shell: bash
        run: bash make/build.sh
      - name: 'Test ApiDiff'
        shell: bash
        run: bash make/build.sh --skip-download -- test
