name: Build and Test APIDiff

on:
  push:
    branches-ignore:
      - master
      - pr/*

jobs:

  linux-x64:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4

      - name: 'Set up Java Development Kit'
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17

      - name: 'Build APIDiff'
        shell: bash
        run: bash make/build.sh

      - name: 'Self-test APIDiff'
        shell: bash
        run: bash make/build.sh --skip-download -- test
