name: 'Test (windows)'

on:
  workflow_call:

env:
  MSYS2_PATH_TYPE: minimal
  CHERE_INVOKING: 1

jobs:
  test:
    name: 'ApiDiff'
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: 'Keep text file line-ending intact'
        run: git config --global core.autocrlf input
      - name: 'Check out repository'
        uses: actions/checkout@v4
      - name: 'Install MSYS2'
        uses: msys2/setup-msys2@v2.22.0
        with:
          install: 'autoconf tar unzip zip make'
          path-type: minimal
      - name: 'Set up Java Development Kit'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
      - name: 'Build ApiDiff'
        shell: msys2 {0}
        run: bash make/build.sh
      - name: 'Test ApiDiff'
        shell: msys2 {0}
        run: bash make/build.sh --skip-download -- test
