name: Build and Test ApiDiff

on:
  push:
    branches-ignore:
      - master
      - pr/*

jobs:
  test-linux:
    uses: ./.github/workflows/test-linux.yml
  test-windows:
    uses: ./.github/workflows/test-windows.yml
